[package]
name = "rust_tmpl"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.75"
chrono = "0.4.33"
dotenv = "0.15.0"
env_logger = "0.10.1"
figment = { version = "0.10.12", features = ["env", "toml"] }
log = "0.4.20"
once_cell = "1.18.0"
parse-display = "0.8.2"
serde = { version = "1.0.193", features = ["derive"] }
thiserror = "1.0.50"
tracing = "0.1.40"
tracing-subscriber = { version = "0.3.18", features = ["env-filter"] }
